title: Jekyll Blog
author: Alantbarlow
email: alantbarlow@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Basic blog utilizing Jekyll and Github Pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
